<script setup lang="ts">
import { computed, ref } from 'vue';
import { useGameLocale } from '../../composables/useGameLocale';
import { createSudokuGame, enterDigit } from './engine';
const { locale } = useGameLocale(); const game = ref(createSudokuGame()); const selected = ref<number | null>(null);
const copy = computed(() => locale.value === 'en' ? { title: 'Sudoku', intro: 'Fill every row, column, and box with digits 1–9.', reset: 'New puzzle', select: 'Selected cell', won: 'Puzzle complete!', hint: 'Choose a blank cell, then a digit.' } : { title: '스도쿠', intro: '각 행·열·3×3 칸에 1부터 9까지 채워 보세요.', reset: '새 퍼즐', select: '선택한 칸', won: '퍼즐을 완성했어요!', hint: '빈칸을 고른 뒤 숫자를 눌러 주세요.' });
function choose(index: number) { if (!game.value.givens[index] && game.value.status === 'playing') selected.value = index; }
function digit(value: number) { if (selected.value !== null) game.value = enterDigit(game.value, selected.value, value); }
function reset() { game.value = createSudokuGame(); selected.value = null; }
</script>
<template><section class="sudoku" aria-labelledby="sudoku-title"><header><p class="eyebrow">IT-BOX · LOGIC</p><h1 id="sudoku-title">{{ copy.title }}</h1><p>{{ copy.intro }}</p></header><div class="board" role="grid" aria-label="Sudoku board"><button v-for="(value, index) in game.board" :key="index" type="button" role="gridcell" :class="{ given: game.givens[index], selected: selected === index }" :aria-label="`Row ${Math.floor(index / 9) + 1}, column ${index % 9 + 1}`" @click="choose(index)">{{ value || '' }}</button></div><p class="status" aria-live="polite">{{ game.status === 'won' ? copy.won : selected === null ? copy.hint : `${copy.select}: ${Math.floor(selected / 9) + 1}, ${selected % 9 + 1}` }}</p><div class="digits" role="group" aria-label="Digits"><button v-for="value in 9" :key="value" type="button" @click="digit(value)">{{ value }}</button></div><button class="reset" type="button" @click="reset">{{ copy.reset }}</button></section></template>
<style scoped>.sudoku{display:grid;justify-items:center;gap:1rem;width:min(100%,38rem);margin:0 auto;color:var(--text-color);text-align:center}header h1{margin:0 0 .4rem;font-size:clamp(2rem,7vw,3rem)}header p:last-child{margin:0;color:var(--muted-color)}.eyebrow{margin:0 0 .25rem;color:#8b5cf6;font-size:.75rem;font-weight:800;letter-spacing:.15em}.board{display:grid;grid-template-columns:repeat(9,1fr);width:min(100%,27rem);gap:1px;border:3px solid #6d28d9;background:#6d28d9}.board button{aspect-ratio:1;border:0;color:var(--text-color);background:var(--surface-background);font-size:clamp(.9rem,4vw,1.4rem);cursor:pointer}.board button:nth-child(3n){border-right:2px solid #6d28d9}.board button:nth-child(n+28):nth-child(-n+36),.board button:nth-child(n+55):nth-child(-n+63){border-top:2px solid #6d28d9}.board button.given{color:#8b5cf6;font-weight:800}.board button.selected{background:#ddd6fe;color:#4c1d95}.status{min-height:1.5rem;margin:0;color:var(--muted-color)}.digits{display:flex;flex-wrap:wrap;justify-content:center;gap:.4rem}.digits button,.reset{border:0;border-radius:.5rem;padding:.65rem .9rem;color:#fff;background:#7c3aed;font-weight:700;cursor:pointer}.reset{background:#6d28d9}</style>
