<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useGameLocale } from '../../composables/useGameLocale';
import { createFlappyGame, flap, stepFlappy } from './engine';
const { locale } = useGameLocale(); const game = ref(createFlappyGame()); const frame = ref<number>();
const copy = computed(() => locale.value === 'en' ? { title: 'Flappy Jump', intro: 'Tap or press Space to fly through the gaps.', start: 'Start', reset: 'New run', score: 'Score', idle: 'Press Space or tap to start.', over: 'Game over — try again.' } : { title: '플래피 점프', intro: '탭하거나 스페이스를 눌러 틈 사이를 날아가세요.', start: '시작', reset: '새 게임', score: '점수', idle: '스페이스 또는 화면을 눌러 시작하세요.', over: '게임 오버 — 다시 도전해 보세요.' });
function stop() { if (frame.value !== undefined) { cancelAnimationFrame(frame.value); frame.value = undefined; } }
function loop(time: number) { const previous = (loop as typeof loop & { last?: number }).last ?? time; (loop as typeof loop & { last?: number }).last = time; game.value = stepFlappy(game.value, time - previous); if (game.value.status === 'playing') frame.value = requestAnimationFrame(loop); else stop(); }
function play() { if (game.value.status === 'game-over') game.value = createFlappyGame(); game.value = flap(game.value); stop(); (loop as typeof loop & { last?: number }).last = undefined; frame.value = requestAnimationFrame(loop); }
function reset() { stop(); game.value = createFlappyGame(); }
function key(event: KeyboardEvent) { if (event.code === 'Space') { event.preventDefault(); play(); } }
onMounted(() => window.addEventListener('keydown', key)); onBeforeUnmount(() => { stop(); window.removeEventListener('keydown', key); });
</script>
<template><section class="flappy" aria-labelledby="flappy-title"><header><p class="eyebrow">IT-BOX · ARCADE</p><h1 id="flappy-title">{{ copy.title }}</h1><p>{{ copy.intro }}</p></header><div class="stats"><span>{{ copy.score }} <strong>{{ game.score }}</strong></span></div><button class="sky" type="button" aria-label="Flap" @click="play"><span class="pipe top" v-for="(pipe, index) in game.pipes" :key="`t${index}`" :style="{ left: `${pipe.x / game.width * 100}%`, height: `${pipe.gapY / game.height * 100}%` }"/><span class="pipe bottom" v-for="(pipe, index) in game.pipes" :key="`b${index}`" :style="{ left: `${pipe.x / game.width * 100}%`, top: `${(pipe.gapY + pipe.gap) / game.height * 100}%`, height: `${(game.height - pipe.gapY - pipe.gap) / game.height * 100}%` }"/><span class="bird" :style="{ left: `${game.birdX / game.width * 100}%`, top: `${game.birdY / game.height * 100}%` }"><i class="bird-body"/><i class="bird-wing"/><i class="bird-eye"/></span></button><p class="status" aria-live="polite">{{ game.status === 'game-over' ? copy.over : game.status === 'idle' ? copy.idle : '' }}</p><div class="actions"><button type="button" @click="play">{{ game.status === 'idle' ? copy.start : copy.start }}</button><button type="button" @click="reset">{{ copy.reset }}</button></div></section></template>
<style scoped>.flappy{display:grid;justify-items:center;gap:1rem;width:min(100%,38rem);margin:0 auto;color:var(--text-color);text-align:center}header h1{margin:0 0 .4rem;font-size:clamp(2rem,7vw,3rem)}header p:last-child{margin:0;color:var(--muted-color)}.eyebrow{margin:0 0 .25rem;color:#0ea5e9;font-size:.75rem;font-weight:800;letter-spacing:.15em}.stats{width:min(100%,22rem);text-align:right;color:var(--muted-color)}.stats strong{color:var(--text-color)}.sky{position:relative;width:min(100%,22rem);aspect-ratio:360/520;overflow:hidden;border:4px solid #0c4a6e;border-radius:1rem;background:linear-gradient(#7dd3fc,#bae6fd 70%,#fde68a);cursor:pointer}.pipe{position:absolute;width:15%;border:2px solid #166534;background:#22c55e}.pipe.top{top:0;border-radius:0 0 .4rem .4rem}.pipe.bottom{border-radius:.4rem .4rem 0 0}.bird{position:absolute;display:block;width:2.15rem;height:1.5rem;transform:translate(-50%,-50%);border-radius:58% 48% 48% 58%;background:#facc15;filter:drop-shadow(1px 2px 0 rgba(120,53,15,.3))}.bird-body{position:absolute;inset:0;border-radius:inherit;background:#facc15}.bird-body::after{position:absolute;top:42%;right:-.55rem;width:.65rem;height:.38rem;content:"";border-radius:0 70% 70% 0;background:#f97316}.bird-wing{position:absolute;top:.58rem;left:.28rem;width:.82rem;height:.48rem;transform:rotate(-18deg);border-radius:70% 25% 70% 25%;background:#eab308}.bird-eye{position:absolute;top:.27rem;right:.45rem;width:.28rem;height:.28rem;border-radius:50%;background:#111827}.status{min-height:1.5rem;margin:0;color:var(--muted-color)}.actions{display:flex;gap:.6rem}.actions button{border:0;border-radius:.6rem;padding:.7rem 1.15rem;color:#fff;background:#0284c7;font-weight:700;cursor:pointer}.actions button+button{color:var(--text-color);background:var(--control-background)}</style>
