<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useBestScore } from '../../composables/useBestScore';
import { useGameLocale } from '../../composables/useGameLocale';
import { createTypingGame, typeCharacter } from './engine';
const PHRASES = ['small steps make progress', 'practice makes things easier', 'build something useful'];
const { locale } = useGameLocale(); const phrase = ref(PHRASES[0]); const game = ref(createTypingGame(phrase.value)); const { best, updateBest } = useBestScore('typing');
const copy = computed(() => locale.value === 'en' ? { title: 'Type Sprint', intro: 'Type the phrase as quickly and accurately as you can.', mistakes: 'Mistakes', best: 'Best score', reset: 'New phrase', won: 'Nice sprint!', hint: 'Start typing to begin.' } : { title: '타이핑 스프린트', intro: '문장을 빠르고 정확하게 입력해 보세요.', mistakes: '오타', best: '최고 점수', reset: '새 문장', won: '멋진 기록이에요!', hint: '키보드로 입력을 시작하세요.' });
function play(event: KeyboardEvent) { if (event.key.length !== 1) return; event.preventDefault(); game.value = typeCharacter(game.value, event.key); if (game.value.status === 'won') updateBest(Math.max(0, 100 - game.value.mistakes * 5)); }
function reset() { phrase.value = PHRASES[Math.floor(Math.random() * PHRASES.length)]; game.value = createTypingGame(phrase.value); }
onMounted(() => window.addEventListener('keydown', play)); onBeforeUnmount(() => window.removeEventListener('keydown', play));
</script>
<template><section class="typing" aria-labelledby="typing-title"><header><p class="eyebrow">IT-BOX · SKILL</p><h1 id="typing-title">{{ copy.title }}</h1><p>{{ copy.intro }}</p></header><div class="stats"><span>{{ copy.mistakes }} <strong>{{ game.mistakes }}</strong></span><span>{{ copy.best }} <strong>{{ best ?? '—' }}</strong></span></div><div class="phrase" aria-live="polite"><span v-for="(character, index) in game.phrase" :key="index" :class="{ typed: index < game.progress, current: index === game.progress }">{{ character === ' ' ? '·' : character }}</span></div><p class="status" aria-live="polite">{{ game.status === 'won' ? copy.won : copy.hint }}</p><button class="reset" type="button" @click="reset">{{ copy.reset }}</button></section></template>
<style scoped>.typing{display:grid;justify-items:center;gap:1rem;width:min(100%,42rem);margin:0 auto;color:var(--text-color);text-align:center}header h1{margin:0 0 .4rem;font-size:clamp(2rem,7vw,3rem)}header p:last-child{margin:0;color:var(--muted-color)}.eyebrow{margin:0 0 .25rem;color:#14b8a6;font-size:.75rem;font-weight:800;letter-spacing:.15em}.stats{display:flex;justify-content:space-between;width:100%;color:var(--muted-color)}.stats strong{color:var(--text-color)}.phrase{width:100%;padding:1.5rem .8rem;border:2px solid var(--border-color);border-radius:.8rem;color:var(--muted-color);background:var(--surface-background);font:700 clamp(1.2rem,4vw,2rem)/1.6 ui-monospace,SFMono-Regular,monospace;overflow-wrap:anywhere}.phrase span.typed{color:#14b8a6}.phrase span.current{border-bottom:3px solid #f59e0b;color:var(--text-color)}.status{min-height:1.5rem;margin:0;color:var(--muted-color)}.reset{border:0;border-radius:.6rem;padding:.7rem 1.15rem;color:#fff;background:#0f766e;font-weight:700;cursor:pointer}</style>
