import { tool as csvToJson } from './csv-to-json';
import { tool as jsonLinesConverter } from './json-lines-converter';
import { tool as jsonToTypescript } from './json-to-typescript';
import { tool as jsonToJsonSchema } from './json-to-json-schema';
import { tool as jsonMerge } from './json-merge';
import { tool as jsonPointer } from './json-pointer';
import { tool as jsonTable } from './json-table';
import { tool as envToJson } from './env-to-json';
import { tool as queryStringConverter } from './query-string-converter';
import { tool as httpHeadersParser } from './http-headers-parser';
import { tool as cookieParser } from './cookie-parser';
import { tool as httpRequestGenerator } from './http-request-generator';
import { tool as htmlToText } from './html-to-text';
import { tool as htmlLinkExtractor } from './html-link-extractor';
import { tool as unicodeNormalizer } from './unicode-normalizer';
import { tool as invisibleCharacterDetector } from './invisible-character-detector';
import { tool as lineEndingConverter } from './line-ending-converter';
import { tool as stringEscapeConverter } from './string-escape-converter';
import { tool as textSetOperations } from './text-set-operations';
import { tool as wordFrequencyCounter } from './word-frequency-counter';
import { tool as cssGradientGenerator } from './css-gradient-generator';
import { tool as cssBoxShadowGenerator } from './css-box-shadow-generator';
import { tool as cssBorderRadiusGenerator } from './css-border-radius-generator';
import { tool as cssClampCalculator } from './css-clamp-calculator';
import { tool as colorContrastChecker } from './color-contrast-checker';
import { tool as dataSizeConverter } from './data-size-converter';
import { tool as durationConverter } from './duration-converter';
import { tool as imageResizer } from './image-resizer';
import { tool as imageConverter } from './image-converter';
import { tool as fileHashCalculator } from './file-hash-calculator';

export const additionalDataTools = [csvToJson, jsonLinesConverter, jsonToTypescript, jsonToJsonSchema, jsonMerge, jsonPointer, jsonTable, envToJson];
export const additionalWebTools = [queryStringConverter, httpHeadersParser, cookieParser, httpRequestGenerator, htmlToText, htmlLinkExtractor];
export const additionalTextTools = [unicodeNormalizer, invisibleCharacterDetector, lineEndingConverter, stringEscapeConverter, textSetOperations, wordFrequencyCounter];
export const additionalDevelopmentTools = [cssGradientGenerator, cssBoxShadowGenerator, cssBorderRadiusGenerator, cssClampCalculator, colorContrastChecker];
export const additionalImageTools = [imageResizer, imageConverter];
export const additionalCryptoTools = [fileHashCalculator];
export const additionalMeasurementTools = [dataSizeConverter, durationConverter];
